package com.lithouse.common.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable ( tableName = Schema.AppKey.tableName )
public class AppKeyItem extends BaseModel {
	private String appKey;
	private String developerId;
	private String appId;
	
	public AppKeyItem ( ) {} 
	
	public AppKeyItem ( String developerId ) {		
		setDeveloperId ( developerId ) ; 
	}
	
	@DynamoDBHashKey ( attributeName = Schema.AppKey.appKey )
	@DynamoDBAutoGeneratedKey
	public String getAppKey ( ) {
		return appKey;
	}
	
	public void setAppKey ( String appKey ) {
		this.appKey = appKey;
	}

	@DynamoDBAttribute ( attributeName = Schema.AppKey.developerId )
	public String getDeveloperId ( ) {
		return developerId;
	}

	public void setDeveloperId ( String developerId ) {
		verifyTextFieldEmpty ( developerId, Schema.App.developerId );
		this.developerId = developerId;
	}

	@DynamoDBRangeKey ( attributeName = Schema.AppKey.appId )
	@DynamoDBAutoGeneratedKey
	public String getAppId () {
		return appId;
	}

	public void setAppId ( String appId ) {
		this.appId = appId;
	}
}

