package com.lithouse.common.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement ( name = "contact" )
@XmlAccessorType ( XmlAccessType.FIELD )
@DynamoDBTable ( tableName = Schema.ContactMessage.tableName )
public class ContactMessageItem extends BaseModel  {
	private String messageId;
	private String developerId;	
	private String emailAddress;
	private String messageText;	
	
	public ContactMessageItem ( ) { }
	
	@DynamoDBHashKey ( attributeName = Schema.ContactMessage.messageId )
	@DynamoDBAutoGeneratedKey
	public String getMessageId () {
		return messageId;
	}

	public void setMessageId ( String messageId ) {
		this.messageId = messageId;
	}

	@DynamoDBAttribute ( attributeName = Schema.ContactMessage.developerId )
	public String getDeveloperId () {
		return developerId;
	}

	public void setDeveloperId ( String developerId ) {
		this.developerId = developerId;
	}

	@DynamoDBAttribute ( attributeName = Schema.ContactMessage.emailAddress )
	public String getEmailAddress () {
		return emailAddress;
	}

	public void setEmailAddress ( String emailAddress ) {
		this.emailAddress = emailAddress;
	}

	@DynamoDBAttribute ( attributeName = Schema.ContactMessage.messageText )
	public String getMessageText () {
		return messageText;
	}

	public void setMessageText ( String messageText ) {
		this.messageText = messageText;
	}

}

