package com.lithouse.common.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable ( tableName = Schema.GroupKey.tableName )
public class GroupKeyItem extends BaseModel {
	private String groupKey;
	private String developerId;
	private String groupId;
	
	public GroupKeyItem ( ) {} 
	
	public GroupKeyItem ( String developerId ) {		
		setDeveloperId ( developerId ) ; 
	}
	
	@DynamoDBHashKey ( attributeName = Schema.GroupKey.groupKey )
	@DynamoDBAutoGeneratedKey
	public String getGroupKey ( ) {
		return groupKey;
	}
	
	public void setGroupKey ( String groupKey ) {
		this.groupKey = groupKey;
	}

	@DynamoDBAttribute ( attributeName = Schema.GroupKey.developerId )
	public String getDeveloperId ( ) {
		return developerId;
	}

	public void setDeveloperId ( String developerId ) {
		verifyTextFieldEmpty ( developerId, Schema.Group.developerId );
		this.developerId = developerId;
	}

	@DynamoDBRangeKey ( attributeName = Schema.GroupKey.groupId )
	@DynamoDBAutoGeneratedKey
	public String getGroupId () {
		return groupId;
	}

	public void setGroupId ( String groupId ) {
		this.groupId = groupId;
	}
	
}

