package com.lithouse.common.model;



import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement ( name = "registration" )
@DynamoDBTable ( tableName = Schema.Registration.tableName )
public class RegistrationItem extends BaseModel  {
	private String registrationId;
	private String code;	
	private String deviceType;
	private String registerDate;
	
	public RegistrationItem ( ) { }
	
	@DynamoDBHashKey ( attributeName = Schema.Registration.registrationId )
	@DynamoDBAutoGeneratedKey
	public String getRegistrationId () {
		return registrationId;
	}

	public void setRegistrationId ( String registrationId ) {
		this.registrationId = registrationId;
	}

	@DynamoDBAttribute ( attributeName = Schema.Registration.code )
	public String getCode () {
		return code;
	}

	public void setCode ( String code ) {
		this.code = code;
	}

	@DynamoDBAttribute ( attributeName = Schema.Registration.deviceType )
	public String getDeviceType () {
		return deviceType;
	}

	public void setDeviceType  ( String deviceType ) {
		this.deviceType = deviceType;
	}
	
	@DynamoDBAttribute ( attributeName = Schema.Registration.registerDate )
	public String getRegisterDate () {
		return registerDate;
	}

	public void setRegisterDate  ( String registerDate ) {
		this.registerDate = registerDate;
	}
	
}

